apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: tester
      image: busybox
      command: ['sh', '-c', 'echo Credentails: $USERNAME:$PASSWORD  && sleep 360']
      env:
      - name: USERNAME
        valueFrom:
          secretRef:
            name: my-secret
            key: username
      - name: PASSWORD
        valueFrom:
          secretRef:
            name: my-secret
            key: password