/*
The License
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/thegrumpylion/passbolt-secrets/pkg/apis/passboltsecrets/v1alpha1"
	scheme "github.com/thegrumpylion/passbolt-secrets/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PassboltSecretsGetter has a method to return a PassboltSecretInterface.
// A group's client should implement this interface.
type PassboltSecretsGetter interface {
	PassboltSecrets(namespace string) PassboltSecretInterface
}

// PassboltSecretInterface has methods to work with PassboltSecret resources.
type PassboltSecretInterface interface {
	Create(ctx context.Context, passboltSecret *v1alpha1.PassboltSecret, opts v1.CreateOptions) (*v1alpha1.PassboltSecret, error)
	Update(ctx context.Context, passboltSecret *v1alpha1.PassboltSecret, opts v1.UpdateOptions) (*v1alpha1.PassboltSecret, error)
	UpdateStatus(ctx context.Context, passboltSecret *v1alpha1.PassboltSecret, opts v1.UpdateOptions) (*v1alpha1.PassboltSecret, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.PassboltSecret, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PassboltSecretList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PassboltSecret, err error)
	PassboltSecretExpansion
}

// passboltSecrets implements PassboltSecretInterface
type passboltSecrets struct {
	client rest.Interface
	ns     string
}

// newPassboltSecrets returns a PassboltSecrets
func newPassboltSecrets(c *PassboltsecretsV1alpha1Client, namespace string) *passboltSecrets {
	return &passboltSecrets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the passboltSecret, and returns the corresponding passboltSecret object, and an error if there is any.
func (c *passboltSecrets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PassboltSecret, err error) {
	result = &v1alpha1.PassboltSecret{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("passboltsecrets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PassboltSecrets that match those selectors.
func (c *passboltSecrets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PassboltSecretList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PassboltSecretList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("passboltsecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested passboltSecrets.
func (c *passboltSecrets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("passboltsecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a passboltSecret and creates it.  Returns the server's representation of the passboltSecret, and an error, if there is any.
func (c *passboltSecrets) Create(ctx context.Context, passboltSecret *v1alpha1.PassboltSecret, opts v1.CreateOptions) (result *v1alpha1.PassboltSecret, err error) {
	result = &v1alpha1.PassboltSecret{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("passboltsecrets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(passboltSecret).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a passboltSecret and updates it. Returns the server's representation of the passboltSecret, and an error, if there is any.
func (c *passboltSecrets) Update(ctx context.Context, passboltSecret *v1alpha1.PassboltSecret, opts v1.UpdateOptions) (result *v1alpha1.PassboltSecret, err error) {
	result = &v1alpha1.PassboltSecret{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("passboltsecrets").
		Name(passboltSecret.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(passboltSecret).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *passboltSecrets) UpdateStatus(ctx context.Context, passboltSecret *v1alpha1.PassboltSecret, opts v1.UpdateOptions) (result *v1alpha1.PassboltSecret, err error) {
	result = &v1alpha1.PassboltSecret{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("passboltsecrets").
		Name(passboltSecret.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(passboltSecret).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the passboltSecret and deletes it. Returns an error if one occurs.
func (c *passboltSecrets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("passboltsecrets").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *passboltSecrets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("passboltsecrets").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched passboltSecret.
func (c *passboltSecrets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PassboltSecret, err error) {
	result = &v1alpha1.PassboltSecret{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("passboltsecrets").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
