/*
The License
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// PassboltSecretListerExpansion allows custom methods to be added to
// PassboltSecretLister.
type PassboltSecretListerExpansion interface{}

// PassboltSecretNamespaceListerExpansion allows custom methods to be added to
// PassboltSecretNamespaceLister.
type PassboltSecretNamespaceListerExpansion interface{}
