/*
The License
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	passboltsecretsv1alpha1 "github.com/thegrumpylion/passbolt-secrets/pkg/apis/passboltsecrets/v1alpha1"
	versioned "github.com/thegrumpylion/passbolt-secrets/pkg/client/clientset/versioned"
	internalinterfaces "github.com/thegrumpylion/passbolt-secrets/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/thegrumpylion/passbolt-secrets/pkg/client/listers/passboltsecrets/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PassboltSecretInformer provides access to a shared informer and lister for
// PassboltSecrets.
type PassboltSecretInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PassboltSecretLister
}

type passboltSecretInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPassboltSecretInformer constructs a new informer for PassboltSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPassboltSecretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPassboltSecretInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPassboltSecretInformer constructs a new informer for PassboltSecret type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPassboltSecretInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PassboltsecretsV1alpha1().PassboltSecrets(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PassboltsecretsV1alpha1().PassboltSecrets(namespace).Watch(context.TODO(), options)
			},
		},
		&passboltsecretsv1alpha1.PassboltSecret{},
		resyncPeriod,
		indexers,
	)
}

func (f *passboltSecretInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPassboltSecretInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *passboltSecretInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&passboltsecretsv1alpha1.PassboltSecret{}, f.defaultInformer)
}

func (f *passboltSecretInformer) Lister() v1alpha1.PassboltSecretLister {
	return v1alpha1.NewPassboltSecretLister(f.Informer().GetIndexer())
}
