apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
- kind: ServiceAccount
  name: passbolt-secrets-sa
  namespace: passbolt-secrets
roleRef:
  kind: ClusterRole
  name: secrets-manager
  apiGroup: rbac.authorization.k8s.io