apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-manager
rules:
- apiGroups: [""]
  resources: ["secrets", "events"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["passboltsecrets.greatlion.tech"]
  resources: ["passboltsecrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]