apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: passboltsecrets.passboltsecrestscontroller.greatlion.tech
spec:
  group: passboltsecrestscontroller.greatlion.tech
  versions: 
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                secret:
                  type: string
                username:
                  type: string
                

  names:
    plural: passboltsecrets
    singular: passboltsecret
    kind: PassboltSecret
  scope: Namespaced
