apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: passboltsecrets.passboltsecrestscontroller.greatlion.tech
spec:
  group: passboltsecrestscontroller.greatlion.tech
  names:
    plural: passboltsecrets
    singular: passboltsecret
    kind: PassboltSecret
  scope: Namespaced
  versions: 
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                source:
                  type: object
                  properties:
                    name:
                      type: string
                    id:
                      type: string
                name:
                  type: string
                secretKey:
                  type: string
                usernameKey:
                  type: string
                urlKey:
                  type: string

