/*
The License
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/thegrumpylion/passbolt-secrets/pkg/apis/passboltsecrets/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePassboltSecrets implements PassboltSecretInterface
type FakePassboltSecrets struct {
	Fake *FakePassboltsecretsV1alpha1
	ns   string
}

var passboltsecretsResource = schema.GroupVersionResource{Group: "passboltsecrets.gratlion.tech", Version: "v1alpha1", Resource: "passboltsecrets"}

var passboltsecretsKind = schema.GroupVersionKind{Group: "passboltsecrets.gratlion.tech", Version: "v1alpha1", Kind: "PassboltSecret"}

// Get takes name of the passboltSecret, and returns the corresponding passboltSecret object, and an error if there is any.
func (c *FakePassboltSecrets) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PassboltSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(passboltsecretsResource, c.ns, name), &v1alpha1.PassboltSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PassboltSecret), err
}

// List takes label and field selectors, and returns the list of PassboltSecrets that match those selectors.
func (c *FakePassboltSecrets) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PassboltSecretList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(passboltsecretsResource, passboltsecretsKind, c.ns, opts), &v1alpha1.PassboltSecretList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PassboltSecretList{ListMeta: obj.(*v1alpha1.PassboltSecretList).ListMeta}
	for _, item := range obj.(*v1alpha1.PassboltSecretList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested passboltSecrets.
func (c *FakePassboltSecrets) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(passboltsecretsResource, c.ns, opts))

}

// Create takes the representation of a passboltSecret and creates it.  Returns the server's representation of the passboltSecret, and an error, if there is any.
func (c *FakePassboltSecrets) Create(ctx context.Context, passboltSecret *v1alpha1.PassboltSecret, opts v1.CreateOptions) (result *v1alpha1.PassboltSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(passboltsecretsResource, c.ns, passboltSecret), &v1alpha1.PassboltSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PassboltSecret), err
}

// Update takes the representation of a passboltSecret and updates it. Returns the server's representation of the passboltSecret, and an error, if there is any.
func (c *FakePassboltSecrets) Update(ctx context.Context, passboltSecret *v1alpha1.PassboltSecret, opts v1.UpdateOptions) (result *v1alpha1.PassboltSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(passboltsecretsResource, c.ns, passboltSecret), &v1alpha1.PassboltSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PassboltSecret), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePassboltSecrets) UpdateStatus(ctx context.Context, passboltSecret *v1alpha1.PassboltSecret, opts v1.UpdateOptions) (*v1alpha1.PassboltSecret, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(passboltsecretsResource, "status", c.ns, passboltSecret), &v1alpha1.PassboltSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PassboltSecret), err
}

// Delete takes name of the passboltSecret and deletes it. Returns an error if one occurs.
func (c *FakePassboltSecrets) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(passboltsecretsResource, c.ns, name), &v1alpha1.PassboltSecret{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePassboltSecrets) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(passboltsecretsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PassboltSecretList{})
	return err
}

// Patch applies the patch and returns the patched passboltSecret.
func (c *FakePassboltSecrets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PassboltSecret, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(passboltsecretsResource, c.ns, name, pt, data, subresources...), &v1alpha1.PassboltSecret{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PassboltSecret), err
}
