/*
The License
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/thegrumpylion/passbolt-secrets/pkg/client/clientset/versioned/typed/passboltsecrets/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakePassboltsecretsV1alpha1 struct {
	*testing.Fake
}

func (c *FakePassboltsecretsV1alpha1) PassboltSecrets(namespace string) v1alpha1.PassboltSecretInterface {
	return &FakePassboltSecrets{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakePassboltsecretsV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
